# Generated by Django 5.0.6 on 2024-06-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image_review_wishlist_wishlistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit Card')], max_length=10)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('card_cvc', models.CharField(blank=True, max_length=3, null=True)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.order')),
            ],
        ),
    ]
